export const ophelData = {
  "metadata": {
    "title": "Choices for Change – Strategic Document",
    "organization": "OPHEL",
    "version_note": "Structured extraction generated by ChatGPT",
    "generated_on": "2025-09-26"
  },
  "organization_profile": {
    "scale_and_reach": {
      "farmers_sourcing_millions": 0.4,
      "manufacturing_facilities_approx": 10,
      "employees_primary_workforce_approx": 9000,
      "countries_approx": 50,
      "revenue_usd_millions": 11.6
    },
    "innovation_and_support": {
      "farmers_getting_sustainability_support_plus": 10000,
      "innovation_centers": 9
    },
    "portfolio": [
      "cocoa",
      "coffee",
      "sesame",
      "vanilla",
      "maize"
    ],
    "positioning": "Global leader in naturally good food & beverage ingredients and solutions"
  },
  "strategy": {
    "foundation": "Supply chain excellence",
    "pillars": [
      "Prosperous farmers",
      "Thriving communities",
      "Climate action",
      "Regenerating the living world"
    ],
    "objective": "Make sustainability real for customers by integrating data, traceability, and verified impact"
  },
  "pillars": {
    "Prosperous farmers": {
      "support_mechanisms": {
        "training_and_skills": [
          "Good Agricultural Practices (GAP)",
          "Post-harvest handling",
          "Inclusion of women and youth",
          "Intercropping and agroforestry",
          "Diversification and professionalizing farmer groups",
          "Literacy, numeracy, and business skills",
          "Personalized farm development plans via farmer information system"
        ],
        "resources": [
          "Improved varieties",
          "Credit",
          "Fertilizer inputs",
          "Tools and equipment"
        ]
      },
      "targets": {
        "2030": {
          "livelihoods_households_supported": 15000,
          "living_income_households": 5000,
          "women_farmers_supported": 2000,
          "youth_supported": 1000
        },
        "2025": {
          "livelihoods_households_supported": 3000,
          "living_income_households_pathway": 1200,
          "women_farmers_supported": 800,
          "youth_supported": 300
        },
        "current_status": {
          "livelihoods_households_in_pilots": 200,
          "living_income_households_supported_to_date": 40,
          "women_farmers_supported": 50,
          "youth_supported": 20
        }
      },
      "quotes": [
        {
          "speaker": "Ophel Holdings Team",
          "theme": "Empowering communities in Uganda; fair opportunities for farmers; education; sustainable growth"
        }
      ]
    },
    "Thriving communities": {
      "focus_areas": [
        "Child labor monitoring and remediation (safe spaces for children during harvest)",
        "Education support (scholarships, mentorship, literacy)",
        "Community nutrition and health (Workforce Nutrition Alliance guidance)",
        "Village Savings & Loan Associations (VSLAs) and vocational training",
        "Human rights protections and policies"
      ],
      "targets": {
        "2030": {
          "empowering_farmers_partner_count": 500,
          "children_supported": 5000,
          "eco_friendly_packaging": "100% across facilities",
          "human_rights_compliance": "Comprehensive policies meeting/exceeding international standards"
        },
        "2025": {
          "empowering_farmers_partner_count": 150,
          "children_supported": 1500,
          "packaging": "Recyclable packaging and energy-saving measures in main facility",
          "human_rights_policy": "Developed and implemented across supply chain"
        },
        "current_status": {
          "farmers_in_pilot": 10,
          "children_in_literacy_pilot": 50,
          "sustainability_packaging_status": "Researching sustainable options; assessing carbon footprint",
          "human_rights_policy_status": "Committed to ethical sourcing; policy and training modules in development"
        }
      }
    },
    "Climate action": {
      "goals": {
        "scope1_2_reduction_percent_min": 50,
        "scope3_reduction_percent_min": 30
      },
      "tools_and_programs": {
        "footprint_and_monitoring": [
          "AtSource+ Digital Footprint Calculator (28 metrics farm-to-customer)",
          "Carbon Sequestration Monitoring (AI-based tree cover and loss analysis)",
          "Carbon Scenario Planner (design and cost climate actions)"
        ],
        "sector_and_reporting": [
          "Cocoa & Forests Initiative",
          "Agriculture Sector Roadmap to 1.5°C",
          "Global Coffee Platform",
          "Food and Land Use Coalition",
          "SBTi commitments and CDP reporting"
        ]
      },
      "actions": [
        "Install biomass boilers and solar; switch to green grid where available",
        "Power more equipment with renewables at own farms",
        "Support local decarbonization agendas",
        "Implement climate-smart agriculture: varietal selection, nutrient management, shade/cover crops, residue management, water and wastewater management, integrated pest management, renewable energy and efficiency"
      ]
    },
    "Regenerating the living world": {
      "strategies": {
        "end_deforestation": [
          "Geo-spatial risk assessments",
          "Polygon mapping and end-to-end traceability",
          "Satellite-based near real-time alerts for deforestation",
          "Supplier engagement and due diligence compliance",
          "Landscape partnerships in high-risk areas"
        ],
        "promote_conservation_agroforestry": [
          "Agroforestry with training, credit, and planting materials",
          "Conservation around farms: windbreaks, hedgerows, buffers, tree lots, protected areas",
          "Protect wetlands and water catchments"
        ],
        "natural_capital_accounting": "Track natural capital costs (starting with cocoa) from farmer groups to processing",
        "living_landscapes": [
          "Multi-stakeholder partnerships for governance, protection of nature, and essential services (nutrition, health, sanitation, education)",
          "Context-specific solutions for soil, water, biodiversity, and climate (fertility management, composting, cover crops, erosion control, irrigation efficiency, wastewater treatment, IPM, low-carbon fertilizers)"
        ]
      },
      "targets": {
        "2030": {
          "regenerative_agriculture_hectares": 10000,
          "beneficial_trees_distributed": 2000000,
          "living_landscape_partnerships": 5,
          "forest_positive_supply_chains": "All direct supply chains deforestation-free",
          "tree_carbon_stock": "Increase in five strategic landscapes"
        },
        "2025": {
          "regenerative_agriculture_hectares": 5000,
          "beneficial_trees_distributed": 1000000,
          "living_landscape_partnerships": 2,
          "deforestation_monitoring": "Transparent monitoring across all supply chains; action plans in high-risk supply chains",
          "farmer_plots_mapped_over": 10000,
          "carbon_sequestration_tool": "Tool under development to assess aboveground biomass at scale"
        },
        "current_status": {
          "regenerative_agriculture_hectares": 1000,
          "native_trees_distributed_cumulative": 150000,
          "living_landscape_partnerships": 1
        }
      }
    }
  },
  "supply_chain_excellence": {
    "traceability": {
      "country_coverage": {
        "cocoa_origins": 9,
        "coffee_origins": 18,
        "nuts_origins": 15,
        "spices_origins": 10
      },
      "digital_tools": [
        "Farmer registration & GPS farm mapping",
        "On-farm mobile app & portal (surveys, training, activities)",
        "Contracting & traceability apps (agreements, inputs, pricing, receipts, logistics, stock, loans, payments)",
        "OPHEL Direct (farmer sales, advice, financing, supplies)",
        "OPHEL Track & Trace (farm plots to customers; EUDR backbone)"
      ]
    },
    "verification": {
      "protocol": "AtSource Verification Protocol",
      "audits": "Independent third-party audits; consistent and fair decisions",
      "supplier_code": "OPHEL Agri Supplier Code (ESG principles)",
      "supplier_coverage_percent_2023_direct": 99
    },
    "risk_and_compliance": [
      "EU Deforestation Regulation (end of 2024)",
      "Corporate Sustainability Due Diligence Directive",
      "US Customs enforcement (human rights)",
      "Child Labour Monitoring and Remediation Systems (CLMRS) in cocoa origins",
      "Strict quality & food safety standards; free from contaminants and heavy metals"
    ],
    "data_and_insights": [
      "Sustainability datamarts and SAP-based financial linkage",
      "Environmental & social data portals",
      "Regulatory data display dashboard",
      "Power BI analytics at all levels"
    ]
  },
  "customer_offerings": {
    "OPSourceV": {
      "target_user": "Customers starting out / managing reputational risk",
      "capabilities": [
        "Traceability to farmer group level or estates",
        "Risk & performance assessment vs reference practices",
        "Country-level risk profiles",
        "Generic carbon & water footprints",
        "Deforestation due diligence",
        "Third-party verification every three years"
      ]
    },
    "OPSource+": {
      "target_user": "Customers wanting a detailed picture at source",
      "adds_to_OPSourceV": [
        "Risk & performance assessment beyond reference practices",
        "Granular, supply-chain-specific metrics and insights",
        "Advanced environmental footprints based on primary data",
        "Annual third-party verification",
        "Targeted programs with field stories covering outcomes"
      ]
    },
    "OPSource": {
      "target_user": "Customers aiming to drive net-positive impact at scale",
      "capabilities": [
        "Bespoke, co-created programs with communities, NGOs, and governments",
        "Landscape regeneration and community prosperity",
        "Transformative impact beyond the supply chain"
      ]
    }
  },
  "uganda_commitment": {
    "themes": [
      "Empower farmers with sustainable livelihoods",
      "Support children's access to quality education",
      "Foster community development and resilience"
    ],
    "approach": "Build strong relationships; small, genuine steps that scale with growth"
  },
  "links_and_resources": {
    "blogs": [
      "https://www.ofi.com/news-and-events/blog/child-labor-monitoring-and-remediation.html",
      "https://www.ofi.com/news-and-events/blog/helping-farming-communities-meet-their-own-health-and-nutrition-needs.html"
    ],
    "videos": [
      "https://www.youtube.com/watch?v=0PLoDVGgLBg"
    ],
    "methodology": [
      "https://www.atsource.io/methodology.html"
    ]
  }
} as const;

// Helper functions to format data for display
export const formatNumber = (num: number): string => {
  if (num >= 1000000) {
    return `${(num / 1000000).toFixed(1)}M`;
  }
  if (num >= 1000) {
    return `${(num / 1000).toFixed(1)}K`;
  }
  return num.toString();
};

export const getOrganizationStats = () => {
  const { scale_and_reach, innovation_and_support } = ophelData.organization_profile;
  return [
    {
      label: "Farmers Sourcing",
      value: `${scale_and_reach.farmers_sourcing_millions}M`,
      description: "Million farmers in our sourcing network"
    },
    {
      label: "Countries",
      value: `${scale_and_reach.countries_approx}+`,
      description: "Countries where we operate"
    },
    {
      label: "Employees",
      value: formatNumber(scale_and_reach.employees_primary_workforce_approx),
      description: "Primary workforce globally"
    },
    {
      label: "Revenue",
      value: `$${scale_and_reach.revenue_usd_millions}M`,
      description: "USD millions in revenue"
    },
    {
      label: "Innovation Centers",
      value: innovation_and_support.innovation_centers.toString(),
      description: "Centers driving innovation"
    },
    {
      label: "Farmers Supported",
      value: `${formatNumber(innovation_and_support.farmers_getting_sustainability_support_plus)}+`,
      description: "Farmers receiving sustainability support"
    }
  ];
};

export const getStrategyPillars = () => {
  return ophelData.strategy.pillars.map(pillar => ({
    title: pillar,
    data: ophelData.pillars[pillar as keyof typeof ophelData.pillars]
  }));
};

export const getPortfolioItems = () => {
  return ophelData.organization_profile.portfolio.map(item => ({
    name: item.charAt(0).toUpperCase() + item.slice(1),
    slug: item
  }));
};
